# ### Hyprland ###
# Apps
$terminal = foot
$browser1 = waterfox
$browser2 = librewolf
$editor = nvim
$fileExplorer = thunar
env = EDITOR,nvim
env = VISUAL,nvim

# Touchpad
$touchpadDisableTyping = true
$touchpadScrollFactor = 0.3
$workspaceSwipeFingers = 4
$gestureFingers = 3
$gestureFingersMore = 4

# Blur
$blurEnabled = true
$blurSpecialWs = true
$blurPopups = true
$blurInputMethods = true
$blurSize = 4
$blurPasses = 2
$blurXray = false

# Shadow
$shadowEnabled = true
$shadowRange = 10
$shadowRenderPower = 2
$shadowColour = rgba($surfaced4)

# Gaps
$workspaceGaps = 10
$windowGapsIn = 2
$windowGapsOut = 4
$singleWindowGapsOut = 4

# Window styling
$windowOpacity = 0.9
$windowRounding = 7

$windowBorderSize = 2
$activeWindowBorderColour = rgba($primarye6)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

# Misc
$volumeStep = 5  # In percent
$cursorTheme = Skyrim-by-ru5tyshark-cursors
$cursorSize = 27


# -----------------------------------------------------
# DEFINIÇÃO DE APPS (Seus Apps do Arquivo 1)
# # -----------------------------------------------------
# $terminal = foot
# $browser = zen-browser
# $editor = codium
# $fileExplorer = thunar

# -----------------------------------------------------
# SUAS VARIÁVEIS DE ATALHO (Do Arquivo 1)
# -----------------------------------------------------

# --- Workspaces ---
$kbMoveWinToWs = Super+Alt
$kbMoveWinToWsGroup = Ctrl+Super+Alt
$kbGoToWs = Super
$kbGoToWsGroup = Ctrl+Super

$kbNextWs = Ctrl+Super, right
$kbPrevWs = Ctrl+Super, left

$kbToggleSpecialWs = Super, W

# --- Grupos de Janelas ---
$kbWindowGroupCycleNext = Alt, Tab
$kbWindowGroupCyclePrev = Shift+Alt, Tab
$kbUngroup = Super, U
$kbToggleGroup = Super, Comma

# --- Ações de Janela ---
$kbMoveWindow = Super, Z
$kbResizeWindow = Super, X
$kbWindowPip = Super+Alt, Backslash
$kbPinWindow = Super, P
$kbWindowFullscreen = Super, F
$kbWindowBorderedFullscreen = Super+Alt, F
$kbToggleWindowFloating = Super+Alt, Space
$kbCloseWindow = Super, Q

# --- Toggles Especiais ---
$kbSystemMonitor = Ctrl+Shift, Escape
$kbMusic = Super, M
$kbCommunication = Super, D
$kbTodo = Super, R

# --- Misc / Sistema ---
$kbSession = Ctrl+Alt, Delete
$kbClearNotifs = Ctrl+Alt, C
$kbShowPanels = Super, K
$kbLock = Super, L
$kbRestoreLock = Super+Alt, L

# Outras variáveis de sistema (Volume/Cursor)
$volumeStep = 3
